/*
Given a string, we have to find out all subsequences of it. A String is a subsequence of a given String, that is generated by deleting some character of a given string without changing its order.

Examples:

Input : abc
Output : a, b, c, ab, bc, ac, abc

Input : aaa
Output : a, aa, aaa*/
#include <bits/stdc++.h>
using namespace std;
void subsequences(string input, string output)
{
    if (input.empty())
    {
        cout << output << " ";
        return;
    }

    // here we will take the character and put in our output
    subsequences(input.substr(1), output + input[0]);

    // here we don't take the character
    subsequences(input.substr(1), output);
}
int main()
{
    string str = "abc";
    int n = str.length();
    // so we will recursion technique here
    // this uses a pick and don't pick concept
    subsequences(str, "");
}